_update_symlinks() {
    stable="$(ls /usr/bin | grep wxrc- | sed 's/wxrc-\(.*\)/\1/' | sort | head -n 1)"
    dev="$(ls /usr/bin | grep wxrc- | sed 's/wxrc-\(.*\)/\1/' | sort | tail -n 1)"
    gtk="$(ls /usr/lib/wx/config | grep $stable | sed 's/.*\(gtk.\).*/\1/' | sort | tail -n 1)"
    if [[ -z "$stable" && -z "$dev" ]]; then
        # if there is no version left installed then delete all symlinks
        rm -f /usr/bin/wx-config
        rm -f /usr/bin/wxrc
        rm -f /usr/share/aclocal/wxwin.m4
        rm -f /usr/share/bakefile/presets/wx_presets.py
        rm -f /usr/share/bakefile/presets/wx_xrc.bkl
        rm -f /usr/share/bakefile/presets/wx_win32.bkl
        rm -f /usr/share/bakefile/presets/wx_unix.bkl
        rm -f /usr/share/bakefile/presets/wx.bkl
    else
        # symlink stable wx-config, favoring gtk3 over gtk2
        ln -sf /usr/lib/wx/config/$gtk-unicode-$stable /usr/bin/wx-config
        # symlink dev wxrc, wxwin.m4, and bakefile presets
        ln -sf /usr/bin/wxrc-$dev /usr/bin/wxrc
        ln -sf /usr/share/aclocal/wxwin-$dev.m4 /usr/share/aclocal/wxwin.m4
        ln -sf /usr/share/bakefile/presets/wx_presets-$dev.py /usr/share/bakefile/presets/wx_presets.py
        ln -sf /usr/share/bakefile/presets/wx_xrc-$dev.bkl /usr/share/bakefile/presets/wx_xrc.bkl
        ln -sf /usr/share/bakefile/presets/wx_win32-$dev.bkl /usr/share/bakefile/presets/wx_win32.bkl
        ln -sf /usr/share/bakefile/presets/wx_unix-$dev.bkl /usr/share/bakefile/presets/wx_unix.bkl
        ln -sf /usr/share/bakefile/presets/wx-$dev.bkl /usr/share/bakefile/presets/wx.bkl
    fi
}

post_install() {
    _update_symlinks
}

post_remove() {
    _update_symlinks
}
